// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ID struct {
	// public_key of the peer (we no longer use the public key as the peer ID, but use it to verify messages)
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// address is the network address of the peer
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// id is the computed hash of the public key
	Id                   []byte   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{0}
}
func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (dst *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(dst, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *ID) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ID) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type Header struct {
	// Supervisor's public key.
	SupervisorID *ID `protobuf:"bytes,1,opt,name=supervisorID,proto3" json:"supervisorID,omitempty"`
	// Previous block id
	LastBlockID *BlockID `protobuf:"bytes,2,opt,name=lastBlockID,proto3" json:"lastBlockID,omitempty"`
	// Number of transactions
	NumTxs   int64 `protobuf:"varint,3,opt,name=numTxs,proto3" json:"numTxs,omitempty"`
	TotalTxs int64 `protobuf:"varint,4,opt,name=totalTxs,proto3" json:"totalTxs,omitempty"`
	Height   int64 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	// Time of block intialization
	Time *Timestamp `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	// Sender's signature of message.
	Signature []byte `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	// Merkle root hash of the transactions
	RootHash []byte `protobuf:"bytes,8,opt,name=rootHash,proto3" json:"rootHash,omitempty"`
	// Child block ID having hash
	BlockID              *BlockID `protobuf:"bytes,9,opt,name=blockID,proto3" json:"blockID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{1}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetSupervisorID() *ID {
	if m != nil {
		return m.SupervisorID
	}
	return nil
}

func (m *Header) GetLastBlockID() *BlockID {
	if m != nil {
		return m.LastBlockID
	}
	return nil
}

func (m *Header) GetNumTxs() int64 {
	if m != nil {
		return m.NumTxs
	}
	return 0
}

func (m *Header) GetTotalTxs() int64 {
	if m != nil {
		return m.TotalTxs
	}
	return 0
}

func (m *Header) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Header) GetTime() *Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Header) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Header) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *Header) GetBlockID() *BlockID {
	if m != nil {
		return m.BlockID
	}
	return nil
}

type BlockID struct {
	BlockHash            []byte   `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockID) Reset()         { *m = BlockID{} }
func (m *BlockID) String() string { return proto.CompactTextString(m) }
func (*BlockID) ProtoMessage()    {}
func (*BlockID) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{2}
}
func (m *BlockID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockID.Unmarshal(m, b)
}
func (m *BlockID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockID.Marshal(b, m, deterministic)
}
func (dst *BlockID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockID.Merge(dst, src)
}
func (m *BlockID) XXX_Size() int {
	return xxx_messageInfo_BlockID.Size(m)
}
func (m *BlockID) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockID.DiscardUnknown(m)
}

var xxx_messageInfo_BlockID proto.InternalMessageInfo

func (m *BlockID) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type ChildBlock struct {
	Header               *Header     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TxsData              *TxsData    `protobuf:"bytes,2,opt,name=txsData,proto3" json:"txsData,omitempty"`
	LastVotes            *VoteCommit `protobuf:"bytes,3,opt,name=lastVotes,proto3" json:"lastVotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChildBlock) Reset()         { *m = ChildBlock{} }
func (m *ChildBlock) String() string { return proto.CompactTextString(m) }
func (*ChildBlock) ProtoMessage()    {}
func (*ChildBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{3}
}
func (m *ChildBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChildBlock.Unmarshal(m, b)
}
func (m *ChildBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChildBlock.Marshal(b, m, deterministic)
}
func (dst *ChildBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChildBlock.Merge(dst, src)
}
func (m *ChildBlock) XXX_Size() int {
	return xxx_messageInfo_ChildBlock.Size(m)
}
func (m *ChildBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_ChildBlock.DiscardUnknown(m)
}

var xxx_messageInfo_ChildBlock proto.InternalMessageInfo

func (m *ChildBlock) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ChildBlock) GetTxsData() *TxsData {
	if m != nil {
		return m.TxsData
	}
	return nil
}

func (m *ChildBlock) GetLastVotes() *VoteCommit {
	if m != nil {
		return m.LastVotes
	}
	return nil
}

// Transactions Data
type TxsData struct {
	Tx                   [][]byte `protobuf:"bytes,1,rep,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxsData) Reset()         { *m = TxsData{} }
func (m *TxsData) String() string { return proto.CompactTextString(m) }
func (*TxsData) ProtoMessage()    {}
func (*TxsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{4}
}
func (m *TxsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxsData.Unmarshal(m, b)
}
func (m *TxsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxsData.Marshal(b, m, deterministic)
}
func (dst *TxsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxsData.Merge(dst, src)
}
func (m *TxsData) XXX_Size() int {
	return xxx_messageInfo_TxsData.Size(m)
}
func (m *TxsData) XXX_DiscardUnknown() {
	xxx_messageInfo_TxsData.DiscardUnknown(m)
}

var xxx_messageInfo_TxsData proto.InternalMessageInfo

func (m *TxsData) GetTx() [][]byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

// Validator
type Validator struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PubKey               []byte   `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Stakingpower         int64    `protobuf:"varint,3,opt,name=stakingpower,proto3" json:"stakingpower,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{5}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (dst *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(dst, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Validator) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Validator) GetStakingpower() int64 {
	if m != nil {
		return m.Stakingpower
	}
	return 0
}

// VoteInfo
type VoteInfo struct {
	Validator            *Validator `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	SignedCurrentBlock   bool       `protobuf:"varint,2,opt,name=signed_current_block,json=signedCurrentBlock,proto3" json:"signed_current_block,omitempty"`
	Signature            []byte     `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VoteInfo) Reset()         { *m = VoteInfo{} }
func (m *VoteInfo) String() string { return proto.CompactTextString(m) }
func (*VoteInfo) ProtoMessage()    {}
func (*VoteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{6}
}
func (m *VoteInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteInfo.Unmarshal(m, b)
}
func (m *VoteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteInfo.Marshal(b, m, deterministic)
}
func (dst *VoteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteInfo.Merge(dst, src)
}
func (m *VoteInfo) XXX_Size() int {
	return xxx_messageInfo_VoteInfo.Size(m)
}
func (m *VoteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VoteInfo proto.InternalMessageInfo

func (m *VoteInfo) GetValidator() *Validator {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *VoteInfo) GetSignedCurrentBlock() bool {
	if m != nil {
		return m.SignedCurrentBlock
	}
	return false
}

func (m *VoteInfo) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ChildBlockMessage struct {
	Vote                 *VoteInfo   `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
	ChildBlock           *ChildBlock `protobuf:"bytes,2,opt,name=childBlock,proto3" json:"childBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChildBlockMessage) Reset()         { *m = ChildBlockMessage{} }
func (m *ChildBlockMessage) String() string { return proto.CompactTextString(m) }
func (*ChildBlockMessage) ProtoMessage()    {}
func (*ChildBlockMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{7}
}
func (m *ChildBlockMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChildBlockMessage.Unmarshal(m, b)
}
func (m *ChildBlockMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChildBlockMessage.Marshal(b, m, deterministic)
}
func (dst *ChildBlockMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChildBlockMessage.Merge(dst, src)
}
func (m *ChildBlockMessage) XXX_Size() int {
	return xxx_messageInfo_ChildBlockMessage.Size(m)
}
func (m *ChildBlockMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChildBlockMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChildBlockMessage proto.InternalMessageInfo

func (m *ChildBlockMessage) GetVote() *VoteInfo {
	if m != nil {
		return m.Vote
	}
	return nil
}

func (m *ChildBlockMessage) GetChildBlock() *ChildBlock {
	if m != nil {
		return m.ChildBlock
	}
	return nil
}

type VoteCommit struct {
	BlockID              *BlockID    `protobuf:"bytes,1,opt,name=blockID,proto3" json:"blockID,omitempty"`
	Vote                 []*VoteInfo `protobuf:"bytes,2,rep,name=vote,proto3" json:"vote,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VoteCommit) Reset()         { *m = VoteCommit{} }
func (m *VoteCommit) String() string { return proto.CompactTextString(m) }
func (*VoteCommit) ProtoMessage()    {}
func (*VoteCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{8}
}
func (m *VoteCommit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteCommit.Unmarshal(m, b)
}
func (m *VoteCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteCommit.Marshal(b, m, deterministic)
}
func (dst *VoteCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteCommit.Merge(dst, src)
}
func (m *VoteCommit) XXX_Size() int {
	return xxx_messageInfo_VoteCommit.Size(m)
}
func (m *VoteCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteCommit.DiscardUnknown(m)
}

var xxx_messageInfo_VoteCommit proto.InternalMessageInfo

func (m *VoteCommit) GetBlockID() *BlockID {
	if m != nil {
		return m.BlockID
	}
	return nil
}

func (m *VoteCommit) GetVote() []*VoteInfo {
	if m != nil {
		return m.Vote
	}
	return nil
}

type Message struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Sender's address and public key.
	Sender *ID `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Sender's signature of message.
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// request_nonce is the request/response ID. Null if ID associated to a message is not a request/response.
	RequestNonce uint64 `protobuf:"varint,4,opt,name=request_nonce,json=requestNonce,proto3" json:"request_nonce,omitempty"`
	// message_nonce is the sequence ID.
	MessageNonce uint64 `protobuf:"varint,5,opt,name=message_nonce,json=messageNonce,proto3" json:"message_nonce,omitempty"`
	// reply_flag indicates this is a reply to a request
	ReplyFlag bool `protobuf:"varint,6,opt,name=reply_flag,json=replyFlag,proto3" json:"reply_flag,omitempty"`
	// opcode specifies the message type
	Opcode               uint32   `protobuf:"varint,7,opt,name=opcode,proto3" json:"opcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{9}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Message) GetSender() *ID {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Message) GetRequestNonce() uint64 {
	if m != nil {
		return m.RequestNonce
	}
	return 0
}

func (m *Message) GetMessageNonce() uint64 {
	if m != nil {
		return m.MessageNonce
	}
	return 0
}

func (m *Message) GetReplyFlag() bool {
	if m != nil {
		return m.ReplyFlag
	}
	return false
}

func (m *Message) GetOpcode() uint32 {
	if m != nil {
		return m.Opcode
	}
	return 0
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{10}
}
func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (dst *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(dst, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{11}
}
func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (dst *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(dst, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

type LookupNodeRequest struct {
	Target               *ID      `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupNodeRequest) Reset()         { *m = LookupNodeRequest{} }
func (m *LookupNodeRequest) String() string { return proto.CompactTextString(m) }
func (*LookupNodeRequest) ProtoMessage()    {}
func (*LookupNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{12}
}
func (m *LookupNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupNodeRequest.Unmarshal(m, b)
}
func (m *LookupNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupNodeRequest.Marshal(b, m, deterministic)
}
func (dst *LookupNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupNodeRequest.Merge(dst, src)
}
func (m *LookupNodeRequest) XXX_Size() int {
	return xxx_messageInfo_LookupNodeRequest.Size(m)
}
func (m *LookupNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookupNodeRequest proto.InternalMessageInfo

func (m *LookupNodeRequest) GetTarget() *ID {
	if m != nil {
		return m.Target
	}
	return nil
}

type LookupNodeResponse struct {
	Peers                []*ID    `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupNodeResponse) Reset()         { *m = LookupNodeResponse{} }
func (m *LookupNodeResponse) String() string { return proto.CompactTextString(m) }
func (*LookupNodeResponse) ProtoMessage()    {}
func (*LookupNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{13}
}
func (m *LookupNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupNodeResponse.Unmarshal(m, b)
}
func (m *LookupNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupNodeResponse.Marshal(b, m, deterministic)
}
func (dst *LookupNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupNodeResponse.Merge(dst, src)
}
func (m *LookupNodeResponse) XXX_Size() int {
	return xxx_messageInfo_LookupNodeResponse.Size(m)
}
func (m *LookupNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookupNodeResponse proto.InternalMessageInfo

func (m *LookupNodeResponse) GetPeers() []*ID {
	if m != nil {
		return m.Peers
	}
	return nil
}

type Bytes struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bytes) Reset()         { *m = Bytes{} }
func (m *Bytes) String() string { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()    {}
func (*Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{14}
}
func (m *Bytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes.Unmarshal(m, b)
}
func (m *Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes.Marshal(b, m, deterministic)
}
func (dst *Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes.Merge(dst, src)
}
func (m *Bytes) XXX_Size() int {
	return xxx_messageInfo_Bytes.Size(m)
}
func (m *Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes proto.InternalMessageInfo

func (m *Bytes) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ConnectionMessage struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionMessage) Reset()         { *m = ConnectionMessage{} }
func (m *ConnectionMessage) String() string { return proto.CompactTextString(m) }
func (*ConnectionMessage) ProtoMessage()    {}
func (*ConnectionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{15}
}
func (m *ConnectionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionMessage.Unmarshal(m, b)
}
func (m *ConnectionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionMessage.Marshal(b, m, deterministic)
}
func (dst *ConnectionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionMessage.Merge(dst, src)
}
func (m *ConnectionMessage) XXX_Size() int {
	return xxx_messageInfo_ConnectionMessage.Size(m)
}
func (m *ConnectionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionMessage proto.InternalMessageInfo

func (m *ConnectionMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Timestamp wraps how amino encodes time.
// This is the protobuf well-known type protobuf/timestamp.proto
// See:
// https://github.com/google/protobuf/blob/d2980062c859649523d5fd51d6b55ab310e47482/src/google/protobuf/timestamp.proto#L123-L135
// NOTE/XXX: nanos do not get skipped if they are zero in amino.
type Timestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos                int64    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{16}
}
func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (dst *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(dst, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int64 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

type BaseBlock struct {
	Header               *BaseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ChildBlock           []byte      `protobuf:"bytes,2,opt,name=child_block,json=childBlock,proto3" json:"child_block,omitempty"`
	Validator            []byte      `protobuf:"bytes,3,opt,name=validator,proto3" json:"validator,omitempty"`
	NextValidator        []byte      `protobuf:"bytes,4,opt,name=next_validator,json=nextValidator,proto3" json:"next_validator,omitempty"`
	VoteCommits          []byte      `protobuf:"bytes,5,opt,name=vote_commits,json=voteCommits,proto3" json:"vote_commits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BaseBlock) Reset()         { *m = BaseBlock{} }
func (m *BaseBlock) String() string { return proto.CompactTextString(m) }
func (*BaseBlock) ProtoMessage()    {}
func (*BaseBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{17}
}
func (m *BaseBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseBlock.Unmarshal(m, b)
}
func (m *BaseBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseBlock.Marshal(b, m, deterministic)
}
func (dst *BaseBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseBlock.Merge(dst, src)
}
func (m *BaseBlock) XXX_Size() int {
	return xxx_messageInfo_BaseBlock.Size(m)
}
func (m *BaseBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseBlock.DiscardUnknown(m)
}

var xxx_messageInfo_BaseBlock proto.InternalMessageInfo

func (m *BaseBlock) GetHeader() *BaseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BaseBlock) GetChildBlock() []byte {
	if m != nil {
		return m.ChildBlock
	}
	return nil
}

func (m *BaseBlock) GetValidator() []byte {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *BaseBlock) GetNextValidator() []byte {
	if m != nil {
		return m.NextValidator
	}
	return nil
}

func (m *BaseBlock) GetVoteCommits() []byte {
	if m != nil {
		return m.VoteCommits
	}
	return nil
}

type BaseHeader struct {
	LastBlockID *BlockID `protobuf:"bytes,1,opt,name=lastBlockID,proto3" json:"lastBlockID,omitempty"`
	// Base block ID having hash
	Block_ID *BlockID `protobuf:"bytes,2,opt,name=block_ID,json=blockID,proto3" json:"block_ID,omitempty"`
	Height   int64    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// Simple Merkle root of the current validators who verified the current block
	ValidatorGroupHash []byte `protobuf:"bytes,4,opt,name=validatorGroupHash,proto3" json:"validatorGroupHash,omitempty"`
	// Simple Merkle root of the Validators for the next block
	NextValidatorGroupHash []byte `protobuf:"bytes,5,opt,name=nextValidatorGroupHash,proto3" json:"nextValidatorGroupHash,omitempty"`
	// Time of block intialization
	Time *Timestamp `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	// Merkle root hash of vote from validators from the current block
	LastVoteHash []byte `protobuf:"bytes,7,opt,name=last_vote_hash,json=lastVoteHash,proto3" json:"last_vote_hash,omitempty"`
	// Merkle root hash of the child blocks
	ChildBlockHash []byte `protobuf:"bytes,8,opt,name=child_block_hash,json=childBlockHash,proto3" json:"child_block_hash,omitempty"`
	// Holds the global state trie created by encoded herdius accounts
	StateRoot            []byte   `protobuf:"bytes,9,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseHeader) Reset()         { *m = BaseHeader{} }
func (m *BaseHeader) String() string { return proto.CompactTextString(m) }
func (*BaseHeader) ProtoMessage()    {}
func (*BaseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_73dc4c5f13f08f43, []int{18}
}
func (m *BaseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseHeader.Unmarshal(m, b)
}
func (m *BaseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseHeader.Marshal(b, m, deterministic)
}
func (dst *BaseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseHeader.Merge(dst, src)
}
func (m *BaseHeader) XXX_Size() int {
	return xxx_messageInfo_BaseHeader.Size(m)
}
func (m *BaseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BaseHeader proto.InternalMessageInfo

func (m *BaseHeader) GetLastBlockID() *BlockID {
	if m != nil {
		return m.LastBlockID
	}
	return nil
}

func (m *BaseHeader) GetBlock_ID() *BlockID {
	if m != nil {
		return m.Block_ID
	}
	return nil
}

func (m *BaseHeader) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BaseHeader) GetValidatorGroupHash() []byte {
	if m != nil {
		return m.ValidatorGroupHash
	}
	return nil
}

func (m *BaseHeader) GetNextValidatorGroupHash() []byte {
	if m != nil {
		return m.NextValidatorGroupHash
	}
	return nil
}

func (m *BaseHeader) GetTime() *Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *BaseHeader) GetLastVoteHash() []byte {
	if m != nil {
		return m.LastVoteHash
	}
	return nil
}

func (m *BaseHeader) GetChildBlockHash() []byte {
	if m != nil {
		return m.ChildBlockHash
	}
	return nil
}

func (m *BaseHeader) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func init() {
	proto.RegisterType((*ID)(nil), "protobuf.ID")
	proto.RegisterType((*Header)(nil), "protobuf.Header")
	proto.RegisterType((*BlockID)(nil), "protobuf.BlockID")
	proto.RegisterType((*ChildBlock)(nil), "protobuf.ChildBlock")
	proto.RegisterType((*TxsData)(nil), "protobuf.TxsData")
	proto.RegisterType((*Validator)(nil), "protobuf.Validator")
	proto.RegisterType((*VoteInfo)(nil), "protobuf.VoteInfo")
	proto.RegisterType((*ChildBlockMessage)(nil), "protobuf.ChildBlockMessage")
	proto.RegisterType((*VoteCommit)(nil), "protobuf.VoteCommit")
	proto.RegisterType((*Message)(nil), "protobuf.Message")
	proto.RegisterType((*Ping)(nil), "protobuf.Ping")
	proto.RegisterType((*Pong)(nil), "protobuf.Pong")
	proto.RegisterType((*LookupNodeRequest)(nil), "protobuf.LookupNodeRequest")
	proto.RegisterType((*LookupNodeResponse)(nil), "protobuf.LookupNodeResponse")
	proto.RegisterType((*Bytes)(nil), "protobuf.Bytes")
	proto.RegisterType((*ConnectionMessage)(nil), "protobuf.ConnectionMessage")
	proto.RegisterType((*Timestamp)(nil), "protobuf.Timestamp")
	proto.RegisterType((*BaseBlock)(nil), "protobuf.BaseBlock")
	proto.RegisterType((*BaseHeader)(nil), "protobuf.BaseHeader")
}

func init() { proto.RegisterFile("stream.proto", fileDescriptor_stream_73dc4c5f13f08f43) }

var fileDescriptor_stream_73dc4c5f13f08f43 = []byte{
	// 1044 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcd, 0x6e, 0x1c, 0x45,
	0x10, 0xce, 0xec, 0xae, 0x77, 0x77, 0x6a, 0x27, 0x56, 0xdc, 0x58, 0xd1, 0x10, 0xe2, 0x8d, 0x69,
	0x02, 0xb1, 0x44, 0xb2, 0x89, 0x1c, 0xc4, 0x8f, 0xb8, 0xad, 0x2d, 0xb0, 0x05, 0x89, 0xac, 0x96,
	0x95, 0xeb, 0xa8, 0x77, 0xa6, 0x3d, 0x3b, 0xf2, 0xce, 0xf4, 0x64, 0xba, 0xc7, 0xd8, 0x37, 0x6e,
	0x3c, 0x00, 0x07, 0x5e, 0x81, 0xe7, 0xe0, 0x14, 0x89, 0x0b, 0x47, 0x4e, 0x28, 0xf6, 0x89, 0x23,
	0x8f, 0x80, 0xfa, 0x67, 0x7e, 0xd6, 0xd8, 0x26, 0xa7, 0x99, 0xaa, 0xfa, 0xba, 0xbb, 0x7e, 0xbe,
	0xaa, 0x02, 0x4f, 0xc8, 0x82, 0xd1, 0x74, 0x92, 0x17, 0x5c, 0x72, 0x34, 0xd4, 0x9f, 0x59, 0x79,
	0x74, 0xef, 0x49, 0x9c, 0xc8, 0x79, 0x39, 0x9b, 0x84, 0x3c, 0x7d, 0x1a, 0xf3, 0x98, 0x3f, 0xad,
	0x2c, 0x5a, 0xd2, 0x82, 0xfe, 0x33, 0x07, 0xf1, 0x0b, 0xe8, 0xec, 0xef, 0xa2, 0x0d, 0x80, 0xbc,
	0x9c, 0x2d, 0x92, 0x30, 0x38, 0x66, 0x67, 0xbe, 0xb3, 0xe9, 0x6c, 0x79, 0xc4, 0x35, 0x9a, 0xef,
	0xd8, 0x19, 0xf2, 0x61, 0x40, 0xa3, 0xa8, 0x60, 0x42, 0xf8, 0x9d, 0x4d, 0x67, 0xcb, 0x25, 0x95,
	0x88, 0x56, 0xa1, 0x93, 0x44, 0x7e, 0x57, 0x1f, 0xe8, 0x24, 0x11, 0xfe, 0xbd, 0x03, 0xfd, 0x3d,
	0x46, 0x23, 0x56, 0xa0, 0x67, 0xe0, 0x89, 0x32, 0x67, 0xc5, 0x49, 0x22, 0x78, 0xb1, 0xbf, 0xab,
	0x6f, 0x1d, 0x6d, 0x7b, 0x93, 0xca, 0x9f, 0xc9, 0xfe, 0x2e, 0x59, 0x42, 0xa0, 0xe7, 0x30, 0x5a,
	0x50, 0x21, 0xa7, 0x0b, 0x1e, 0x1e, 0xef, 0xef, 0xea, 0xa7, 0x46, 0xdb, 0x6b, 0xcd, 0x01, 0x6b,
	0x20, 0x6d, 0x14, 0xba, 0x0b, 0xfd, 0xac, 0x4c, 0x0f, 0x4f, 0x85, 0xf6, 0xa2, 0x4b, 0xac, 0x84,
	0xee, 0xc1, 0x50, 0x72, 0x49, 0x17, 0xca, 0xd2, 0xd3, 0x96, 0x5a, 0x56, 0x67, 0xe6, 0x2c, 0x89,
	0xe7, 0xd2, 0x5f, 0x31, 0x67, 0x8c, 0x84, 0x1e, 0x41, 0x4f, 0x26, 0x29, 0xf3, 0xfb, 0xfa, 0xe5,
	0xf7, 0x9a, 0x97, 0x0f, 0x93, 0x94, 0x09, 0x49, 0xd3, 0x9c, 0x68, 0x00, 0xba, 0x0f, 0xae, 0x48,
	0xe2, 0x8c, 0xca, 0xb2, 0x60, 0xfe, 0xc0, 0xa4, 0xab, 0x56, 0xa8, 0xa7, 0x0b, 0xce, 0xe5, 0x1e,
	0x15, 0x73, 0x7f, 0xa8, 0x8d, 0xb5, 0x8c, 0x3e, 0x85, 0xc1, 0xcc, 0xc6, 0xe7, 0x5e, 0x17, 0x5f,
	0x85, 0xc0, 0x8f, 0x60, 0x50, 0x85, 0x79, 0x1f, 0x5c, 0xad, 0xd5, 0x97, 0xda, 0x02, 0xd5, 0x0a,
	0xfc, 0x8b, 0x03, 0xb0, 0x33, 0x4f, 0x16, 0x91, 0x86, 0xa3, 0x2d, 0x15, 0x9f, 0x2a, 0x82, 0x4d,
	0xfa, 0x9d, 0xe6, 0x0d, 0x53, 0x1c, 0x62, 0xed, 0xca, 0x1d, 0x79, 0x2a, 0x76, 0xa9, 0xa4, 0xff,
	0x4d, 0xf7, 0xa1, 0x31, 0x90, 0x0a, 0x81, 0xb6, 0xc1, 0x55, 0x99, 0x7f, 0xc5, 0x25, 0x33, 0xd9,
	0x1e, 0x6d, 0xaf, 0x37, 0x70, 0xa5, 0xde, 0xe1, 0x69, 0x9a, 0x48, 0xd2, 0xc0, 0xf0, 0xfb, 0x30,
	0xb0, 0xf7, 0x28, 0xae, 0xc8, 0x53, 0xdf, 0xd9, 0xec, 0x2a, 0xae, 0xc8, 0x53, 0x3c, 0x07, 0xf7,
	0x15, 0x5d, 0x24, 0x11, 0x95, 0xbc, 0x68, 0x53, 0xcc, 0x59, 0xa6, 0xd8, 0x06, 0x0c, 0xf2, 0x72,
	0xa6, 0x89, 0xa9, 0x5c, 0xf4, 0xa6, 0xbd, 0x37, 0x7f, 0x3d, 0xb8, 0x45, 0xfa, 0x79, 0x39, 0x53,
	0xdc, 0xc4, 0xaa, 0x13, 0xe8, 0x71, 0x92, 0xc5, 0x39, 0xff, 0x81, 0x15, 0x96, 0x05, 0x4b, 0x3a,
	0xfc, 0xb3, 0x03, 0x43, 0xe5, 0xce, 0x7e, 0x76, 0xc4, 0xd1, 0x17, 0xe0, 0x9e, 0x54, 0xcf, 0xda,
	0xfc, 0xb4, 0x2a, 0x5d, 0x7b, 0x64, 0x9f, 0x69, 0xb0, 0xe8, 0x19, 0xac, 0xab, 0x1a, 0xb3, 0x28,
	0x08, 0xcb, 0xa2, 0x60, 0x99, 0x0c, 0x74, 0x01, 0xb4, 0x57, 0x43, 0x82, 0x8c, 0x6d, 0xc7, 0x98,
	0x4c, 0x1d, 0x96, 0x68, 0xd2, 0xbd, 0x44, 0x13, 0xfc, 0x1a, 0xd6, 0x9a, 0x9a, 0xbd, 0x60, 0x42,
	0xd0, 0x98, 0xa1, 0x4f, 0xa0, 0x77, 0xc2, 0x25, 0xb3, 0x8e, 0xa1, 0xe5, 0xf4, 0x2a, 0xff, 0x89,
	0xb6, 0xa3, 0xcf, 0x00, 0xc2, 0xfa, 0xb0, 0xad, 0x5d, 0xab, 0x18, 0xcd, 0xc5, 0xa4, 0x85, 0xc3,
	0x14, 0xa0, 0x29, 0x53, 0x9b, 0x8b, 0xce, 0xff, 0x71, 0xb1, 0x76, 0xac, 0xb3, 0xd9, 0xbd, 0xc9,
	0x31, 0xfc, 0xb7, 0x03, 0x83, 0x2a, 0x18, 0x1f, 0x06, 0xa9, 0xf9, 0xb5, 0x94, 0xad, 0x44, 0xf4,
	0x10, 0xfa, 0x82, 0x65, 0x8a, 0xa1, 0x9d, 0x2b, 0xc6, 0x82, 0xb5, 0xdd, 0x9c, 0x3f, 0xf4, 0x11,
	0xdc, 0x2e, 0xd8, 0xeb, 0x92, 0x09, 0x19, 0x64, 0x3c, 0x0b, 0x99, 0x6e, 0xf3, 0x1e, 0xf1, 0xac,
	0xf2, 0xa5, 0xd2, 0x29, 0x90, 0x7d, 0xd3, 0x82, 0x56, 0x0c, 0xc8, 0x2a, 0x0d, 0x68, 0x03, 0xa0,
	0x60, 0xf9, 0xe2, 0x2c, 0x38, 0x5a, 0xd0, 0x58, 0x77, 0xff, 0x90, 0xb8, 0x5a, 0xf3, 0xcd, 0x82,
	0xc6, 0x6a, 0x5c, 0xf0, 0x3c, 0xe4, 0x91, 0x69, 0xf5, 0xdb, 0xc4, 0x4a, 0xb8, 0x0f, 0xbd, 0x83,
	0x24, 0x8b, 0xf5, 0x97, 0x67, 0x31, 0xfe, 0x0a, 0xd6, 0xbe, 0xe7, 0xfc, 0xb8, 0xcc, 0x5f, 0xf2,
	0x88, 0x11, 0xe3, 0x85, 0x8a, 0x54, 0xd2, 0x22, 0x66, 0xf2, 0xca, 0x01, 0x68, 0x6d, 0xf8, 0x4b,
	0x40, 0xed, 0xa3, 0x22, 0xe7, 0x99, 0x60, 0x08, 0xc3, 0x4a, 0xce, 0x58, 0x21, 0x74, 0xd3, 0x5c,
	0x3e, 0x6a, 0x4c, 0xf8, 0x03, 0x58, 0x99, 0x9e, 0x49, 0x26, 0x10, 0x82, 0x5e, 0xa4, 0xfa, 0xd8,
	0x64, 0x5a, 0xff, 0xe3, 0x27, 0xb0, 0xb6, 0xc3, 0xb3, 0x8c, 0x85, 0x32, 0xe1, 0xd9, 0x35, 0x55,
	0x71, 0xeb, 0xaa, 0xe0, 0xaf, 0xc1, 0xad, 0x27, 0x9d, 0x82, 0x09, 0x16, 0xf2, 0x2c, 0x32, 0x1d,
	0xd9, 0x25, 0x95, 0x88, 0xd6, 0x61, 0x25, 0xa3, 0x19, 0x37, 0xcb, 0xa0, 0x4b, 0x8c, 0x80, 0x7f,
	0x73, 0xc0, 0x9d, 0x52, 0xc1, 0x0c, 0xf5, 0x1f, 0x5f, 0x1a, 0x41, 0x2d, 0x6e, 0x2a, 0xd0, 0xa5,
	0x31, 0xf4, 0x00, 0x46, 0x9a, 0xa5, 0xad, 0x8e, 0xf2, 0xda, 0xc4, 0x55, 0x4c, 0x68, 0x9a, 0xd6,
	0x32, 0xa1, 0xe9, 0xcc, 0x8f, 0x61, 0x35, 0x63, 0xa7, 0x32, 0x68, 0x20, 0x3d, 0x0d, 0xb9, 0xad,
	0xb4, 0xcd, 0x8c, 0xf9, 0x10, 0x3c, 0x45, 0xd1, 0x20, 0xd4, 0xf4, 0x17, 0x9a, 0x0a, 0x1e, 0x19,
	0x9d, 0xd4, 0x1d, 0x21, 0xf0, 0x4f, 0x5d, 0x80, 0xc6, 0xbf, 0xcb, 0x1b, 0xc9, 0x79, 0xa7, 0x8d,
	0xf4, 0x18, 0x86, 0x3a, 0x8c, 0xe0, 0xa6, 0x1d, 0x56, 0xf7, 0x55, 0xb3, 0x8b, 0xba, 0x4b, 0xbb,
	0x68, 0x02, 0xa8, 0x0e, 0xe7, 0xdb, 0x82, 0x97, 0xb9, 0x9e, 0xfc, 0x26, 0xae, 0x2b, 0x2c, 0xe8,
	0x73, 0xb8, 0xbb, 0x14, 0x6d, 0x73, 0xc6, 0x84, 0x79, 0x8d, 0xf5, 0xdd, 0x77, 0xde, 0x43, 0x58,
	0x55, 0x51, 0x06, 0x3a, 0x85, 0x73, 0x75, 0xb1, 0x59, 0x7c, 0x5e, 0x35, 0xec, 0xf5, 0x75, 0x5b,
	0x70, 0xa7, 0x55, 0x49, 0x83, 0x33, 0x3b, 0x70, 0xb5, 0x29, 0xa7, 0x46, 0x6e, 0x00, 0x08, 0x49,
	0x25, 0x0b, 0xd4, 0x6e, 0xd4, 0xcb, 0x50, 0x75, 0xb7, 0xd2, 0x10, 0xce, 0xe5, 0x74, 0xe7, 0xcf,
	0xf3, 0xf1, 0xad, 0xb7, 0xe7, 0x63, 0xe7, 0x9f, 0xf3, 0xb1, 0xf3, 0xe3, 0xc5, 0xd8, 0xf9, 0xf5,
	0x62, 0xec, 0xbc, 0xb9, 0x18, 0x3b, 0x7f, 0x5c, 0x8c, 0x9d, 0xb7, 0x17, 0x63, 0x07, 0xd6, 0x42,
	0x9e, 0x4e, 0xe6, 0xac, 0x88, 0x92, 0x52, 0x18, 0xb7, 0xa7, 0xde, 0x9e, 0x11, 0x0f, 0x94, 0x74,
	0xe0, 0xcc, 0xfa, 0x5a, 0xfd, 0xfc, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x7e, 0x33, 0x1d,
	0x2d, 0x09, 0x00, 0x00,
}
