// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tx/protobuf/stream.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Nonce                uint64   `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Balance              uint64   `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	StorageRoot          string   `protobuf:"bytes,4,opt,name=storage_root,json=storageRoot,proto3" json:"storage_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4680dc0df1e800c, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Transaction) GetStorageRoot() string {
	if m != nil {
		return m.StorageRoot
	}
	return ""
}

func init() {
	proto.RegisterType((*Transaction)(nil), "protobuf.Transaction")
}

func init() { proto.RegisterFile("tx/protobuf/stream.proto", fileDescriptor_d4680dc0df1e800c) }

var fileDescriptor_d4680dc0df1e800c = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xce, 0x3f, 0xcf, 0x82, 0x30,
	0x10, 0xc7, 0xf1, 0xf4, 0x79, 0xf0, 0x5f, 0x61, 0xb1, 0x71, 0xe8, 0x88, 0xba, 0x30, 0xc1, 0xe0,
	0x3b, 0x60, 0x72, 0x24, 0xc4, 0xdd, 0x1c, 0x50, 0x95, 0x44, 0x7a, 0xe6, 0x7a, 0x24, 0xc6, 0x57,
	0x6f, 0x28, 0x76, 0xfc, 0x7c, 0x73, 0xb9, 0xfc, 0xa4, 0xe6, 0x77, 0xf1, 0x22, 0x64, 0x6c, 0xc6,
	0x5b, 0xe1, 0x98, 0x0c, 0x0c, 0xb9, 0xb7, 0x5a, 0x87, 0x7c, 0xf8, 0xc8, 0xf8, 0x42, 0x60, 0x1d,
	0xb4, 0xdc, 0xa3, 0x55, 0x5a, 0xae, 0xa0, 0xeb, 0xc8, 0x38, 0xa7, 0x45, 0x2a, 0xb2, 0x4d, 0x1d,
	0xa8, 0x76, 0x72, 0x61, 0xd1, 0xb6, 0x46, 0xff, 0xa5, 0x22, 0x8b, 0xea, 0x19, 0xd3, 0x7d, 0x03,
	0x4f, 0x98, 0xfa, 0xbf, 0xef, 0x81, 0x6a, 0x2f, 0x13, 0xc7, 0x48, 0x70, 0x37, 0x57, 0x42, 0x64,
	0x1d, 0xf9, 0x77, 0xf1, 0xaf, 0xd5, 0x88, 0x5c, 0x1e, 0xe5, 0xb6, 0xc5, 0x21, 0x7f, 0x18, 0xea,
	0xfa, 0xd1, 0xcd, 0xd3, 0xca, 0xe4, 0x3c, 0xb3, 0x9a, 0x54, 0x89, 0x66, 0xe9, 0xf3, 0xe9, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0x16, 0x9a, 0x8f, 0x11, 0xcd, 0x00, 0x00, 0x00,
}
