// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Address              string               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey            string               `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Nonce                uint64               `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Balance              uint64               `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	StorageRoot          string               `protobuf:"bytes,5,opt,name=storage_root,json=storageRoot,proto3" json:"storage_root,omitempty"`
	Erc20Address         string               `protobuf:"bytes,6,opt,name=erc20_address,json=erc20Address,proto3" json:"erc20_address,omitempty"`
	EBalances            map[string]*EBalance `protobuf:"bytes,7,rep,name=eBalances,proto3" json:"eBalances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Account) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Account) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Account) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetStorageRoot() string {
	if m != nil {
		return m.StorageRoot
	}
	return ""
}

func (m *Account) GetErc20Address() string {
	if m != nil {
		return m.Erc20Address
	}
	return ""
}

func (m *Account) GetEBalances() map[string]*EBalance {
	if m != nil {
		return m.EBalances
	}
	return nil
}

type AccountRegisterRequest struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRegisterRequest) Reset()         { *m = AccountRegisterRequest{} }
func (m *AccountRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRegisterRequest) ProtoMessage()    {}
func (*AccountRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{1}
}

func (m *AccountRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRegisterRequest.Unmarshal(m, b)
}
func (m *AccountRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRegisterRequest.Marshal(b, m, deterministic)
}
func (m *AccountRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRegisterRequest.Merge(m, src)
}
func (m *AccountRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRegisterRequest.Size(m)
}
func (m *AccountRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRegisterRequest proto.InternalMessageInfo

func (m *AccountRegisterRequest) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type EBalance struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance              uint64   `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	LastBlockHeight      uint64   `protobuf:"varint,3,opt,name=last_block_height,json=lastBlockHeight,proto3" json:"last_block_height,omitempty"`
	Nonce                uint64   `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EBalance) Reset()         { *m = EBalance{} }
func (m *EBalance) String() string { return proto.CompactTextString(m) }
func (*EBalance) ProtoMessage()    {}
func (*EBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{2}
}

func (m *EBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EBalance.Unmarshal(m, b)
}
func (m *EBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EBalance.Marshal(b, m, deterministic)
}
func (m *EBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EBalance.Merge(m, src)
}
func (m *EBalance) XXX_Size() int {
	return xxx_messageInfo_EBalance.Size(m)
}
func (m *EBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_EBalance.DiscardUnknown(m)
}

var xxx_messageInfo_EBalance proto.InternalMessageInfo

func (m *EBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EBalance) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *EBalance) GetLastBlockHeight() uint64 {
	if m != nil {
		return m.LastBlockHeight
	}
	return 0
}

func (m *EBalance) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func init() {
	proto.RegisterType((*Account)(nil), "protobuf.Account")
	proto.RegisterMapType((map[string]*EBalance)(nil), "protobuf.Account.EBalancesEntry")
	proto.RegisterType((*AccountRegisterRequest)(nil), "protobuf.AccountRegisterRequest")
	proto.RegisterType((*EBalance)(nil), "protobuf.EBalance")
}

func init() { proto.RegisterFile("stream.proto", fileDescriptor_bb17ef3f514bfe54) }

var fileDescriptor_bb17ef3f514bfe54 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xcb, 0x6a, 0xc3, 0x30,
	0x10, 0xc4, 0xce, 0x7b, 0x93, 0x3e, 0x22, 0x4a, 0x31, 0x85, 0x82, 0x9b, 0x5c, 0x4c, 0x0f, 0xa6,
	0xa4, 0x87, 0x96, 0x1e, 0x0a, 0x31, 0x04, 0x02, 0xbd, 0x04, 0xff, 0x80, 0xb1, 0x95, 0x6d, 0x62,
	0xe2, 0x58, 0xa9, 0x24, 0x17, 0x72, 0xeb, 0x07, 0xf6, 0xa3, 0x8a, 0x24, 0x8b, 0x3c, 0x0e, 0x3d,
	0xd9, 0x33, 0xbb, 0x3b, 0xda, 0xd9, 0x81, 0x81, 0x90, 0x1c, 0xd3, 0x6d, 0xb8, 0xe3, 0x4c, 0x32,
	0xd2, 0xd5, 0x9f, 0xac, 0xfa, 0x1c, 0xfd, 0xba, 0xd0, 0x99, 0x52, 0xca, 0xaa, 0x52, 0x12, 0x0f,
	0x3a, 0xe9, 0x72, 0xc9, 0x51, 0x08, 0xcf, 0xf1, 0x9d, 0xa0, 0x17, 0x5b, 0x48, 0xee, 0x01, 0x76,
	0x55, 0x56, 0xe4, 0x34, 0xd9, 0xe0, 0xde, 0x73, 0x75, 0xb1, 0x67, 0x98, 0x0f, 0xdc, 0x93, 0x1b,
	0x68, 0x95, 0xac, 0xa4, 0xe8, 0x35, 0x7c, 0x27, 0x68, 0xc6, 0x06, 0x28, 0xb9, 0x2c, 0x2d, 0x52,
	0xc5, 0x37, 0x35, 0x6f, 0x21, 0x79, 0x50, 0xeb, 0x30, 0x9e, 0xae, 0x30, 0xe1, 0x8c, 0x49, 0xaf,
	0xa5, 0x05, 0xfb, 0x35, 0x17, 0x33, 0x26, 0xc9, 0x18, 0x2e, 0x90, 0xd3, 0xc9, 0x53, 0x62, 0x37,
	0x6a, 0xeb, 0x9e, 0x81, 0x26, 0xa7, 0xf5, 0x5a, 0xef, 0xd0, 0xc3, 0xc8, 0x68, 0x0a, 0xaf, 0xe3,
	0x37, 0x82, 0xfe, 0xc4, 0x0f, 0xad, 0xb5, 0xb0, 0xb6, 0x15, 0xce, 0x6c, 0xcb, 0xac, 0x94, 0x7c,
	0x1f, 0x1f, 0x46, 0xee, 0x16, 0x70, 0x79, 0x5a, 0x24, 0xd7, 0xd0, 0x50, 0x0e, 0x8d, 0x7d, 0xf5,
	0x4b, 0x02, 0x68, 0x7d, 0xa7, 0x45, 0x85, 0xda, 0x75, 0x7f, 0x42, 0x0e, 0xfa, 0x76, 0x34, 0x36,
	0x0d, 0x6f, 0xee, 0xab, 0x33, 0x7a, 0x81, 0xdb, 0xfa, 0xd9, 0x18, 0x57, 0xb9, 0x90, 0xc8, 0x63,
	0xfc, 0xaa, 0x50, 0xc8, 0xb3, 0x13, 0x3a, 0x67, 0x27, 0x1c, 0xfd, 0x38, 0xd0, 0xb5, 0x82, 0xff,
	0x04, 0x71, 0x74, 0x53, 0xf7, 0xf4, 0xa6, 0x8f, 0x30, 0x2c, 0x52, 0x21, 0x93, 0xac, 0x60, 0x74,
	0x93, 0xac, 0x31, 0x5f, 0xad, 0x65, 0x9d, 0xc7, 0x95, 0x2a, 0x44, 0x8a, 0x9f, 0x6b, 0xfa, 0x90,
	0x57, 0xf3, 0x28, 0xaf, 0x68, 0x0c, 0x43, 0xca, 0xb6, 0xe1, 0x1a, 0xf9, 0x32, 0xaf, 0x84, 0xf1,
	0x19, 0x0d, 0xe6, 0x06, 0x2e, 0x14, 0x5a, 0x38, 0x59, 0x5b, 0xd3, 0xcf, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x9c, 0x6b, 0xb8, 0x49, 0x50, 0x02, 0x00, 0x00,
}
